### ISSUE TITLE
command not found: free(MacBook Pro OS Version10.11.1)

### ISSUE THREAD

**Issue by gavin-k** [fcamblor/oh-my-zsh-agnoster-fcamblor#1]
Hi fcamblor,
I use my mac to install `oh-my-zsh-agnoster-fcamblor`.But the mac report `command not found:free`.And I found your theme source code include `free` command.So I think your code was out of date on the latest OSX.Can you fix this problem?
Thank you! :)

**Comment by fcamblor** [comment]
Seems like fixed in fd2ce31b5ada2833dc7d30a23c34f62b174632f0 :-)
