### ISSUE TITLE
the prompt icon(blue 'arrow' shaped thing) appears like a question mark? 

### ISSUE THREAD

**Issue by xintongw829** [fcamblor/oh-my-zsh-agnoster-fcamblor#3]
pls tell me how to fix this, thanks~
[截屏2022-08-03 下午5.08.47.zip](https://github.com/fcamblor/oh-my-zsh-agnoster-fcamblor/files/9249832/2022-08-03.5.08.47.zip)

my codes are:

Last login: Wed Aug  3 15:43:26 on ttys000
➜  ~ pip3 install powerline-status --user -i https://pypi.tuna.tsinghua.edu.cn/simple   
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting powerline-status
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9c/30/8bd3c62642778af9ad813a526c6ff7dd2f98144d6580ad6fab94ca389265/powerline-status-2.7.tar.gz (233 kB)
     |████████████████████████████████| 233 kB 5.1 MB/s 
Using legacy setup.py install for powerline-status, since package 'wheel' is not installed.
Installing collected packages: powerline-status
    Running setup.py install for powerline-status ... done
Successfully installed powerline-status-2.7
WARNING: You are using pip version 20.1.1; however, version 22.2.1 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -m pip install --upgrade pip' command.
➜  ~ mkdir ~/OpenSource/ 
➜  ~ cd ~/OpenSource 
➜  OpenSource git clone https://github.com/powerline/fonts.git --depth=1
正克隆到 'fonts'...
remote: Enumerating objects: 310, done.
remote: Counting objects: 100% (310/310), done.
remote: Compressing objects: 100% (236/236), done.
remote: Total 310 (delta 75), reused 260 (delta 71), pack-reused 0
接收对象中: 100% (310/310), 10.40 MiB | 22.00 KiB/s, 完成.
处理 delta 中: 100% (75/75), 完成.
➜  OpenSource git clone https://github.com/fcamblor/oh-my-zsh-agnoster-fcamblor.git
正克隆到 'oh-my-zsh-agnoster-fcamblor'...
remote: Enumerating objects: 136, done.
remote: Total 136 (delta 0), reused 0 (delta 0), pack-reused 136
接收对象中: 100% (136/136), 1.14 MiB | 9.00 KiB/s, 完成.
处理 delta 中: 100% (59/59), 完成.
➜  OpenSource cd oh-my-zsh-agnoster-fcamblor/
➜  oh-my-zsh-agnoster-fcamblor git:(master) ./install
Creating symlink from here to your oh-my-zsh themes path...

Done ! (the symlink is ~/.oh-my-zsh/themes/agnoster-fcamblor.zsh-theme)

----------------------------------------------------------------------------------

Options:
All options must be overridden in your .zshrc file.
See README.md for more info.

----------------------------------------------------------------------------------

Requirements:
Vim Powerline patched font: See Powerline for vim for more info.
Z shell (zsh): See oh-my-zsh for more info.
Make sure terminal is using 256-colors mode with export TERM="xterm-256color".
➜  oh-my-zsh-agnoster-fcamblor git:(master)

**Comment by fcamblor** [comment]
It seems like you didn't configured Powerline font in your terminal, as stated in the [readme](https://github.com/fcamblor/oh-my-zsh-agnoster-fcamblor#readme)

**Comment by xintongw829** [comment]
Thx. I forgot to set up font to Source Code Pro for Powerline on my Terminal preference. Now it looks correct.
